services:
  - type: web
    name: sweet-shop-api
    env: python
    plan: starter
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: JWT_REFRESH_SECRET_KEY
        sync: false
      - key: ACCESS_TOKEN_EXPIRES_MINUTES
        value: "15"
      - key: REFRESH_TOKEN_EXPIRES_DAYS
        value: "7"
